// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperAppAPI.Data;

#nullable disable

namespace SuperAppAPI.Migrations.SuperAppDb
{
    [DbContext(typeof(SuperAppDbContext))]
    [Migration("20251018063723_SuperAppDbContextMigration")]
    partial class SuperAppDbContextMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperAppAPI.Models.Domain.OTTDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OTTPlatforms");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.PayementMethods", b =>
                {
                    b.Property<Guid>("PayementMethodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PayementMethodsId");

                    b.ToTable("PayementMethods");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.Payements", b =>
                {
                    b.Property<int>("PayementsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayementsID"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("PayementMethodsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlansDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PayementsID");

                    b.HasIndex("PayementMethodsId");

                    b.HasIndex("PlansDomainId");

                    b.ToTable("Payements");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.PlansDomain", b =>
                {
                    b.Property<Guid>("PlansDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Validity")
                        .HasColumnType("int");

                    b.HasKey("PlansDomainId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.SubscribedPlans", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("PlansDomainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubscribedPlansId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlansDomainId");

                    b.ToTable("SubscribedPlans");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.Payements", b =>
                {
                    b.HasOne("SuperAppAPI.Models.Domain.PayementMethods", "payementMethods")
                        .WithMany()
                        .HasForeignKey("PayementMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperAppAPI.Models.Domain.PlansDomain", "plansDomain")
                        .WithMany()
                        .HasForeignKey("PlansDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payementMethods");

                    b.Navigation("plansDomain");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.SubscribedPlans", b =>
                {
                    b.HasOne("SuperAppAPI.Models.Domain.PlansDomain", "Plans")
                        .WithMany()
                        .HasForeignKey("PlansDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
