// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperAppAPI.Data;

#nullable disable

namespace SuperAppAPI.Migrations
{
    [DbContext(typeof(SuperAppDbContext))]
    [Migration("20251121033837_Initial_Main")]
    partial class Initial_Main
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("SuperAppAPI.Models.Domain.OTTDomain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OTTPlatforms");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.PayementMethods", b =>
                {
                    b.Property<Guid>("PayementMethodsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PayementMethodsId");

                    b.ToTable("PayementMethods");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.Payements", b =>
                {
                    b.Property<int>("PayementsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<Guid>("PayementMethodsId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlansDomainId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("PayementsID");

                    b.HasIndex("PayementMethodsId");

                    b.HasIndex("PlansDomainId");

                    b.ToTable("Payements");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.PlansDomain", b =>
                {
                    b.Property<Guid>("PlansDomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("PlanDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Validity")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlansDomainId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.SubUsers", b =>
                {
                    b.Property<Guid>("SubUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscribedPlansId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubUserId");

                    b.ToTable("SubUsers");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.SubscribedPlans", b =>
                {
                    b.Property<Guid>("SubscribedPlansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlansDomainId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Validity")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubscribedPlansId");

                    b.HasIndex("PlansDomainId");

                    b.ToTable("SubscribedPlans");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.Payements", b =>
                {
                    b.HasOne("SuperAppAPI.Models.Domain.PayementMethods", "payementMethods")
                        .WithMany()
                        .HasForeignKey("PayementMethodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperAppAPI.Models.Domain.PlansDomain", "plansDomain")
                        .WithMany()
                        .HasForeignKey("PlansDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("payementMethods");

                    b.Navigation("plansDomain");
                });

            modelBuilder.Entity("SuperAppAPI.Models.Domain.SubscribedPlans", b =>
                {
                    b.HasOne("SuperAppAPI.Models.Domain.PlansDomain", "Plans")
                        .WithMany()
                        .HasForeignKey("PlansDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
